apiVersion: v1
kind: Service
metadata:
  name: more-license-plate-recognition-service
spec:
  selector:
    app: more-license-plate-recognition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
